kind: pipeline
name: Threadripper Kernel (4.9)

steps:
- name: Getting epyc
  image: najahi/oven:latest
  environment: 
    ID:
      from_secret: ID
    BOT_API_KEY:
      from_secret: BOT_API_KEY

  commands:
    - bash run.sh

