kind: pipeline
name: Retarded Kernel (4.9)

steps:
- name: Getting retarded
  image: okta10/docker:debian
  environment: 
    ID:
      from_secret: ID
    BOT_API_KEY:
      from_secret: BOT_API_KEY

  commands:
    - bash run.sh

