kind: pipeline
name: Retarded Kernel (4.9)

steps:
- name: Getting retarded
  image: debian
  environment: 
    CHANNEL_ID:
      from_secret: CHANNEL_ID
    TELEGRAM_TOKEN:
      from_secret: TELEGRAM_TOKEN

  commands:
    - bash run.sh

