kind: pipeline
name: Retarded Kernel (4.9)

steps:
- name: Getting retarded
  image: xyzuan/xdocker:latest
  environment: 
    ID:
      from_secret: CHANNEL_ID
    BOT_API_KEY:
      from_secret: TELEGRAM_TOKEN

  commands:
    - bash run.sh

